# Generated by Django 4.1 on 2022-09-21 09:36

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.TextField()),
                ('Password', models.TextField()),
                ('Profile_Img', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='converter',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='converter',
            name='id',
        ),
        migrations.AddField(
            model_name='converter',
            name='Done',
            field=models.CharField(default='hello', max_length=400),
        ),
        migrations.AddField(
            model_name='converter',
            name='Todo',
            field=models.TextField(default='USD'),
        ),
        migrations.AddField(
            model_name='converter',
            name='Todo_Id',
            field=models.BigIntegerField(default=uuid.uuid4(), primary_key=True, serialize=True,unique=True),
        ),
    ]
