# Generated by Django 4.1 on 2022-09-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_signup_remove_converter_currency_remove_converter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='Todo_Id',
            field=models.AutoField(default=7989, primary_key=True, serialize=False),
        ),
    ]
