# Generated by Django 4.1 on 2022-09-24 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_alter_converter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='Todo_Id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
